name: CI/CD - Build & Deploy

on:
  push:
    branches:
      - deploy_k8s
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/db_populator
      KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      # - name: Patch deployment YAML with current timestamp
      #   run: |
      #     TIMESTAMP=$(date +%s)
      #     sed "s|REDEPLOY_TIMESTAMP|$TIMESTAMP|" ./k8s/deployment.yml > ./k8s/deployment-patched.yml

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl -n $KUBE_NAMESPACE apply -f ./k8s/deployment-patched.yml --kubeconfig=.kube/config.yaml
